#!/bin/bash
# Push Notification Development Setup Tester
# This tests if your development build can receive push notifications

echo "📱 EXPO PUSH NOTIFICATION DEVELOPMENT TESTER"
echo "============================================"
echo ""

echo "🔧 Step 1: Check Expo CLI and project setup"
if command -v npx expo &> /dev/null; then
    echo "✅ Expo CLI available"

    cd "/home/charles/Internet-of-Tsiken-v2"

    echo "📱 Current Expo project info:"
    npx expo config --type public | head -20
else
    echo "❌ Expo CLI not found - install with: npm install -g @expo/cli"
fi

echo ""
echo "🔧 Step 2: Check if development build supports notifications"
echo "Run this on your development device:"
echo ""
echo "  1. Make sure you're running: npx expo start --dev-client"
echo "  2. Open the app on your phone"
echo "  3. Check console logs for FCM token generation"
echo ""

echo "🔧 Step 3: Test notification permissions in development"
echo "Add this test code to your app to verify permissions:"
echo ""
echo "//////////////// Test Code for App.js ////////////////"
echo "import * as Device from 'expo-device';"
echo "import * as Notifications from 'expo-notifications';"
echo ""
echo "// Add this inside your useEffect after authentication"
echo "console.log('🔔 Testing notification setup...');"
echo "console.log('📱 Device type:', Device.isDevice);"
echo ""
echo "Notifications.getPermissionsAsync().then(perms => {"
echo "  console.log('🎯 Notification permissions:', perms);"
echo "});"
echo ""
echo "if (Device.isDevice) {"
echo "  Notifications.getExpoPushTokenAsync().then(token => {"
echo "    console.log('🔑 Expo push token:', token.data);"
echo "  }).catch(err => {"
echo "    console.log('❌ Token error:', err);"
echo "  });"
echo "}"
echo "//////////////// End Test Code ////////////////"

echo ""
echo "🎯 ANSWERS TO YOUR APK QUESTION:"
echo "================================="
echo ""
echo "📋 Development Mode (NO APK needed):"
echo "  ✅ Expo development client CAN receive push notifications"
echo "  ✅ FCM tokens work in development builds"
echo "  ✅ Your current setup should work WITHOUT publishing"
echo ""
echo "🚨 BUT you needed these fixes (now applied):"
echo "  ✅ Added expo-notifications plugin to app.json"
echo "  ✅ Added Android notification permissions"
echo "  ✅ Notification channel configuration"
echo ""
echo "🔧 Next Steps:"
echo "  1. Stop your current Expo development server"
echo "  2. Run: npx expo prebuild --clear"
echo "  3. Run: npx expo start --dev-client"
echo "  4. Rebuild development client on your phone"
echo "  5. Test push notifications again"
echo ""
echo "📦 Production APK (Alternative approach):"
echo "  • Run: eas build --platform android --profile preview"
echo "  • This creates a proper APK with full FCM integration"
echo "  • More reliable than development builds for notifications"
echo ""
echo "🔍 Debug Development Issues:"
echo "  • Check Expo console logs for FCM token generation"
echo "  • Verify phone notification permissions"
echo "  • Test with app.json changes applied"